#!/usr/bin/env python3

import sys

#The output list size is >= the input size

varmapNumbers = {
    '2': ['a', 'b', 'c'],
    '3': ['d', 'e', 'f'],
    '4': ['g', 'h', 'i'],
    '5': ['j', 'k', 'l'],
    '6': ['m', 'n', 'o'],
    '7': ['p', 'q', 'r', 's'],
    '8': ['t', 'u', 'v'],
    '9': ['w', 'x', 'y', 'z']
}
varmap = varmapNumbers.copy() #phone number keypad letters

for num, letterList in varmapNumbers.items():
    for letter in letterList:
        varmap[letter] = varmapNumbers[num]

def gen_variations(s: str, varmap: dict):
    print(s)
    variations = set([s])

    for i in range(len(s)):
        letter = s[i]
        if not (letter in varmap): continue
        letterVariations = []
            
        for subLetter in varmap[letter]:
            for variationStub in variations:
                variationStub = variationStub[:i] + subLetter + variationStub[(i+1):]
                letterVariations.append(variationStub)

        for variation in letterVariations:
            if not variation in variations:
                print(variation)
        variations.update(letterVariations)

    return variations

if __name__ == "__main__":
    for word in sys.argv[1:]:
        gen_variations(word, varmap)
    for word in sys.stdin:
        word = word.strip()
        if len(word) == 0: continue
        gen_variations(word, varmap)
